provider: "gmail"
smtp_host: "smtp.gmail.com"
smtp_port: 587
username: "shirodkars127@gmail.com"
password: "rijhyg-7sujmi-jEwber"
recipient_email: "shirodkars127@gmail.com"

enable_application_alerts: true
enable_daily_summary: true
enable_weekly_summary: true
